### ISSUE TITLE
How to get pre-training data?

### ISSUE THREAD

**Issue by ZJU-Fangyin** [thunlp/KV-PLM#1]
Hi, I notice that this repositories does not contain the corpus used in pre-training, can you provide it? Thanks.

**Comment by fangxintao** [comment]
跑smiles_bpe.sh时，指定任务为BBBP，在分数据集的时候语句scaf = sp.train_valid_test_split(dataset=seq, smiles_list=sm_list, frac_train=0.8,frac_valid=0.1, frac_test=0.1, include_chirality=False)报错，错误提示为"no molecule provided"，我将数据集分成几段依次尝试，最后发现是smile data的59号句子和61号句子这里放入库函数中会出问题。想问下是否是数据集本身有问题，还是说别的原因？

**Comment by Ellenzzn** [comment]
We have temporarily not uploaded the pre-training corpus because we haven't asked for permission to adapt and distribute the original S2orc literature corpus. The corpus format is quite simple, and I guess that you can easily create a new own corpus under your domain:

1. For KV-PLM*, we recognize the chemical entities (with the help of SciSpacy tool) in literatures and insert their SMILES strings into the original text (e.g., Salicylic acid C1=CC=C(C(=C1)C(=O)O)O is an organic acid), and tokenize the sentences with the SciBERT tokenizer.
2. For KV-PLM, we separately tokenize the recognized entities with a SMILES tokenizer, and insert the ids with offset to the corresponding positions of the normal tokenized sentences.
